import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/layoutWrapper";
import { CollapseStoreProvider } from "@/providers/collapse-store-provider";
import Sidebar from "@/components/sidebar";
import Header from "./(auth)/header";
import { AiFloatingButton } from "@/components/ai-cta-buttons";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Personal Finance App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${publicSans.variable} antialiased`}>
        <CollapseStoreProvider>
          <LayoutWrapper>
            <Sidebar />
            <main className="main pt-6 sm:pt-8 md:h-screen overflow-hidden overflow-y-scroll">
              {children}
              <Header />
              <AiFloatingButton />
            </main>
          </LayoutWrapper>
        </CollapseStoreProvider>
      </body>
    </html>
  );
}
